apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-pv
spec:
  destination:
    name: ''
    namespace: jenkins-ns
    server: https://kubernetes.default.svc
  source:
    path: Project_5/jenkins
    repoURL: https://github.com/Iyadomry/devops.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true