apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: busybox-ns # Replace 'default' with your desired namespace
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"]
  restartPolicy: Never
