apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: jenkins-ns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi